"""Generate the host's Python-compatible Unicode casefold table (no runtime Python)."""
from pathlib import Path
import unicodedata


def generate():
    lines = [
        "// Generated by generate_sync_casefold.py; Unicode " + unicodedata.unidata_version + ".",
        "using System;", "using System.Text;", "namespace DocMind {",
        "public static class UnicodeCaseFold {",
        "public static string Fold(string value) {",
        "var result = new StringBuilder(value.Length);",
        "for (int i = 0; i < value.Length; i++) {",
        "int code = Char.ConvertToUtf32(value, i);",
        "if (code > 0xffff) i++;",
        "switch (code) {",
    ]
    for code in range(0x110000):
        if 0xD800 <= code <= 0xDFFF:
            continue
        char = chr(code)
        folded = char.casefold()
        if folded != char:
            escaped = "".join("\\u%04x" % unit for unit in [int.from_bytes(folded.encode("utf-16-le")[i:i+2], "little") for i in range(0, len(folded.encode("utf-16-le")), 2)])
            lines.append(f'case 0x{code:x}: result.Append("{escaped}"); break;')
    lines += ["default: result.Append(Char.ConvertFromUtf32(code)); break;", "}", "}", "return result.ToString();", "}", "}", "}"]
    Path(__file__).with_name("DocMindUnicodeCaseFold.cs").write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    generate()
